### ISSUE TITLE
Found a Bug

### ISSUE THREAD

**Issue by larkincrain** [beartums/AssemblaMentionsExtension#5]
Hey eric, I installed this on my machine. It's not working. It just... crashes chrome. Can you make sure this is OSX compatible? 

Thoughts?

**Comment by beartums** [comment]
OFFS.

I don't have a good solution for that.  IWOMM.  I unfortunately don't have OSX to test it on.  

Any indication what's making it crash?  Can you install it in a virtual machine and see if it works?  Have you tried it on any other Macs?  What version of OSX are you on?

**Comment by larkincrain** [comment]
Hm. I'm trying to debug it with Chrome Dev Tools. I think it's in the background.js script. Can you add some debugging lines to the console?

Anyway, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/5314801/24294368/3d77c0c6-10a7-11e7-84c8-034aea3b0e0f.png)

**Comment by beartums** [comment]
Oh.  I know what that is. 

Don't worry, that is expected functionality.  Can I close this issue now?

(where would you like me to add debugging lines?  Does it crash right away?  Does it go for a little while and then crash?  Can you get to the options screen?)

**Comment by larkincrain** [comment]
Oh, ok, whew! I'm glad it's expected functionality. I was a little worried there for a minute. No worries then! Feel free to close the issue. Thanks for your prompt response!

**Comment by beartums** [comment]
Ok.  You don't have to be that way

**Comment by beartums** [comment]
@larkincrain Did you try downloading the extension and Loading it from a directory?  That has been more forgiving for me.  Just put the source in a directory, goto manage extensions in chrome, put it in developer mode, then load unpacked extension and select the extension directory
